use crate::{
    config::Config,
    dataset::{number, Dataset},
    io,
};
use anyhow::{ensure, Context, Result};
use serde_json::{json, Value};
use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
    process::Command,
};

pub fn write_sources(
    dataset: &Dataset,
    gallery: &Value,
    stage: &Path,
    config: &Config,
) -> Result<()> {
    let p = &config.capture;
    let summary = &dataset.summary;
    fs::write(
        stage.join(&config.paper.source),
        include_str!("../templates/paper.tex"),
    )?;
    fs::write(stage.join("tex/generated/publication_results.tex"),format!("% Generated by bevy_zeroverse_publication; do not edit.\n\\newcommand{{\\PubAuditRooms}}{{{}}}\n\\newcommand{{\\PubRenderRooms}}{{{}}}\n\\newcommand{{\\PubViewCount}}{{{}}}\n",p.audit_rooms,p.rendered_rooms,p.rendered_rooms*p.cameras*p.playback_steps))?;
    let a = &summary["annotation_metrics"];
    let timing = &summary["capture_wall_seconds"];
    let coverage = &summary["semantic_coverage"];
    let features = summary["feature_room_counts"].as_object().unwrap();
    let mut evaluation = format!(
        r"% Generated from the same manifest as the project page.
\section{{Current architectural evaluation}}
\subsection{{Protocol and architectural audit}}
This cohort was captured with bevy\_zeroverse {version}, generator {generator}, on {audit} consecutive seeds ({start}--{end}), with {cameras} cameras per room, furnishing density {density} and static human density {human}. Every audited room passed the recorded layout, support and camera-clearance checks. The first {rendered} rooms were rendered without appearance filtering at {width}$\times${height}, with {steps} trajectory endpoints: {views} camera/time identities in six aligned modes. The audit contains {signatures} unique structural signatures after centimetre quantization; this bounded diagnostic does not estimate the total procedural space or learning utility.

\begin{{table}}[ht]\centering\small
\begin{{tabular}}{{lrr}}\toprule
Built feature & Rooms & Fraction \\\midrule
",
        version = dataset.identity.crate_version,
        generator = dataset.identity.generator_version,
        audit = p.audit_rooms,
        start = p.seed,
        end = p.seed + p.audit_rooms as u64 - 1,
        cameras = p.cameras,
        density = p.density,
        human = p.human_density,
        rendered = p.rendered_rooms,
        width = p.width,
        height = p.height,
        steps = p.playback_steps,
        views = p.rendered_rooms * p.cameras * p.playback_steps,
        signatures = summary["quantized_structural_signatures"]
    );
    for (key, n) in features {
        evaluation.push_str(&format!(
            "{} & {} / {} & {:.1}\\% \\\\\n",
            tex(key),
            n,
            p.audit_rooms,
            100.0 * number(n) / p.audit_rooms as f64
        ));
    }
    evaluation.push_str("\\bottomrule\\end{tabular}\n\\caption{Architectural features in the complete consecutive population. Features co-occur; fractions do not sum to 100\\%.}\\label{tab:architecture}\n\\end{table}\n\n");
    let numeric = &dataset.metrics["numeric"];
    evaluation.push_str(&format!(r"\subsection{{Geometry, calibration and displayed captures}}
Footprint areas span {area_min:.2}--{area_max:.2} m$^2$, with roof pitch {pitch_min:.2}--{pitch_max:.2}$^\circ$. Figure~\ref{{fig:architecture-levels}} and Figure~\ref{{fig:architecture-envelopes}} pair native RGB with the actual serialized envelope plans and sections. Camera arrows indicate direction, rather than frusta. Solid furnishings are footprint proxies; the sections show roof and floor levels and omit furnishings, pillars and partitions. Structural feature examples are selected independently of rendered appearance; all rooms remain available in the contact sheet and explorer. Metric constraints are not building-code certification.

The page presents all {rendered} rooms, all four cameras and both endpoints in one explorer, with {images} channel images. RGB, depth, normals, semantics, positions, co-visibility, camera calibration and plans share the same room/time identity. RGB preserves renderer tone mapping and sRGB encoding without per-image exposure correction or cropping. All previews use lossless WebP. Depth is an 8-bit axial-depth preview divided by 15 m and clamped; normals store $(n+1)/2$, and positions are affine-normalized by the annotation AABB and clamped. Semantic colors are preserved exactly. These previews are not float32 training labels. Geometric annotations use the first surface, including opaque glass, rather than reflected or refracted optical content.

The native capture protocol uses Auto quality, shadows, SSAO and approximate diffuse GI with {rays} primary rays per probe. Renderer identity and capabilities are recorded in every calibration download. All captured views passed the recorded alignment checks: maximum per-view depth/position p99 error {depth:.3} $\mu$m, reprojection p99 {reprojection:.5} pixels and normal-length error {normal:.3e}. Every view contains at least {classes} semantic classes. {visible_primary}/{primary} rooms with humans in the camera's primary functional zone show person pixels; {invisible_main}/{main_people} rooms with humans anywhere in the main envelope never show person pixels. These are class-level observations, rather than instance-level visibility guarantees.

Scene construction through capture/export takes {time_min:.2}--{time_max:.2} seconds per room (median {median:.2}), excluding application startup. This is a bounded capture run, not a sustained-throughput, unlimited-process memory-stability or photographic-realism qualification.

",area_min=number(&numeric["envelope_footprint_area_m2"]["min"]),area_max=number(&numeric["envelope_footprint_area_m2"]["max"]),pitch_min=number(&numeric["envelope_ceiling_slope_degrees"]["min"]),pitch_max=number(&numeric["envelope_ceiling_slope_degrees"]["max"]),rendered=p.rendered_rooms,images=p.rendered_rooms*p.cameras*p.playback_steps*6,rays=p.gi_rays,depth=number(&a["depth_position_p99_metres"]["max"])*1e6,reprojection=number(&a["reprojection_p99_pixels"]["max"]),normal=number(&a["normal_length_max_error"]["max"]),classes=summary["minimum_semantic_classes"],primary=coverage["rooms_with_camera_primary_zone_humans"],visible_primary=coverage["rooms_with_camera_primary_zone_humans"].as_u64().unwrap()-coverage["camera_primary_zone_human_rooms_without_person_pixels"].as_array().unwrap().len() as u64,invisible_main=coverage["main_envelope_human_rooms_without_person_pixels"].as_array().unwrap().len(),main_people=coverage["rooms_with_main_envelope_humans"],time_min=number(&timing["min"]),time_max=number(&timing["max"]),median=number(&timing["p05_p50_p95"][1])));
    for (name,label,caption) in [
        ("architecture_levels.jpg","architecture-levels","Native RGB and metric plans of structurally selected rooms. Raised and depressed levels, decks and stairs are generated geometry. Cyan marks glazing; orange/blue denote raised/sunken floors; violet denotes mezzanines and stairs."),
        ("architecture_envelopes.jpg","architecture-envelopes","Native RGB paired with the corresponding envelope programs. Floor levels, portals, polygonal outlines and apertures vary; features can be outside a particular camera view."),
        ("architecture_footprints.png","architecture-plans","Twelve metric envelope programs selected by architectural feature coverage from the full consecutive population. Plans are diagrams, not twelve additional RGB renders."),
        ("architecture_annotations.jpg","architecture-annotations","Matched RGB, depth, view-space normals and semantic display previews, camera 0 at t=0. All six annotations, camera identities and endpoint times remain accessible in the explorer."),
    ] {evaluation.push_str(&figure(name,label,caption));}
    let first = &gallery["featured"][0]["seed"];
    evaluation.push_str(&format!(r"\subsection{{Co-visibility in every captured room}}
Production co-visibility accompanies every RGB and geometry view in this cohort. Each valid source pixel stores an exact uint16 membership mask of other capture cameras that see its first surface, with the source bit excluded. One deterministic additive legend is shared across all views. The unified explorer supports all memberships and individual-peer overlays; the selected peer's own tile stays RGB.

Across every room and endpoint, {shared:.1}\% of valid source-pixel observations are visible to at least one peer. This pixel-weighted statistic pools {valid} valid source-pixel observations; it does not count unique 3D points. Exact downloads include 16-bit grayscale membership PNGs, separate 8-bit 0/1 validity PNGs, calibrated transforms and the ordered camera legend. Zero membership with valid=1 is an unshared surface; zero membership with valid=0 is background. Co-visibility and other annotations were captured together, rather than joined from separate runs.

",shared=100.0*number(&summary["co_visibility"]["shared_fraction_valid"]),valid=summary["co_visibility"]["valid_pixels"]));
    evaluation.push_str(&figure("architecture_co_visibility.jpg","architecture-co-visibility",&format!("Seed {first} at t=0: four native RGB views above their production co-visibility annotations. Columns retain the same camera/time identity. All captured rooms expose this annotation in the same explorer.")));
    evaluation.push_str(r"\subsection{Population distributions and publication contract}
Room and object counts retain zero-instance rooms. Camera and photometric histograms state their own sample denominators. Placement heatmaps use 33 path samples per camera and normalize each panel independently. Feature shortcuts do not change population denominators. A seed's bit width and continuous parameter ranges do not establish ten-million-sample diversity; correlations, placement constraints and rendering affect distinguishable outcomes. Frozen SigLIP2 embeddings support separate redundancy audits, but no embedding-rank or downstream-learning result is claimed here.

The project page, paper, figures and calibration archives are built by a single Rust publication pipeline from one completed capture manifest. A compiled generator identity binds crate version, geometry grammar and source/dependency hashes. The publisher validates scene/camera/time identities, every requested channel, exact membership masks, annotation checks and population denominators before staging artifacts. The release/deployment gate checks input and output hashes, preserving explicitly separate historical reference studies. Author-written method text and measurements have distinct roles; publication attestation does not imply photographic or downstream validation.

");
    for (name,label,caption) in [("architecture_features.png","architecture-features","Architectural feature counts and continuous parameter distributions from the complete population; absent features are retained."),("architecture_population.png","architecture-population","Furnishing, lighting and camera variation in the same population. Every panel states its denominator."),("architecture_placement.png","architecture-placement","Chair centers, human centers and camera path samples in normalized room X/Z coordinates, with +Z down. Each panel reports its own sample count and color scale."),("architecture_consecutive.jpg","architecture-consecutive","Every consecutively rendered room, camera 0 at t=0, including dark and sparsely furnished rooms. All four cameras, endpoints and six modes remain in the project-page explorer.")] {evaluation.push_str(&figure(name,label,caption));}
    evaluation.push_str("\\clearpage\n");
    fs::write(
        stage.join("tex/generated/publication_evaluation.tex"),
        evaluation,
    )?;
    Ok(())
}
fn tex(text: &str) -> String {
    text.chars()
        .map(|c| match c {
            '&' => "\\&".into(),
            '%' => "\\%".into(),
            '_' => "\\_".into(),
            '#' => "\\#".into(),
            '$' => "\\$".into(),
            '{' => "\\{".into(),
            '}' => "\\}".into(),
            '\\' => "\\textbackslash{}".into(),
            '^' => "\\textasciicircum{}".into(),
            '~' => "\\textasciitilde{}".into(),
            _ => c.to_string(),
        })
        .collect()
}
fn figure(name: &str, label: &str, caption: &str) -> String {
    format!("\\begin{{figure}}[p]\n\\centering\\includegraphics[width=\\linewidth,height=.82\\textheight,keepaspectratio]{{generated/{name}}}\n\\caption{{{}}}\\label{{fig:{label}}}\n\\end{{figure}}\n\n",tex(caption))
}

pub fn closure(tex_root: &Path, main: &Path) -> Result<BTreeSet<PathBuf>> {
    let expression = regex::Regex::new(r"\\(?:input|includegraphics)(?:\[[^\]]*\])?\{([^}]+)\}")?;
    let mut pending = vec![
        main.to_owned(),
        PathBuf::from("arxiv.sty"),
        PathBuf::from("references.bib"),
    ];
    let mut used = BTreeSet::new();
    while let Some(path) = pending.pop() {
        crate::config::safe_relative(&path)?;
        if used.contains(&path) {
            continue;
        }
        ensure!(
            tex_root.join(&path).is_file(),
            "missing paper dependency: {}",
            path.display()
        );
        if path.extension().is_some_and(|s| s == "tex") {
            let source = fs::read_to_string(tex_root.join(&path))?;
            for matched in expression.captures_iter(&source) {
                let mut dependency = PathBuf::from(&matched[1]);
                if dependency.extension().is_none() {
                    dependency.set_extension("tex");
                }
                pending.push(dependency);
            }
        }
        used.insert(path);
    }
    Ok(used)
}
pub fn compile(stage: &Path, config: &Config, gallery: &Value) -> Result<()> {
    let tex_root = stage.join("tex");
    let build = stage.join("latex");
    fs::create_dir_all(&build)?;
    let main = config
        .paper
        .source
        .strip_prefix("tex")
        .context("paper source must be below tex/")?;
    let status = Command::new("latexmk")
        .args([
            "-pdf",
            "-interaction=nonstopmode",
            "-halt-on-error",
            "-no-shell-escape",
        ])
        .arg(format!("-outdir={}", build.display()))
        .arg(main)
        .current_dir(&tex_root)
        .env("SOURCE_DATE_EPOCH", "946684800")
        .env("FORCE_SOURCE_DATE", "1")
        .env("TZ", "UTC")
        .status()
        .context("latexmk is required for publication refresh")?;
    ensure!(
        status.success(),
        "paper compilation failed; staged output not installed"
    );
    let stem = main.file_stem().unwrap().to_string_lossy();
    let log = fs::read_to_string(build.join(format!("{stem}.log")))?;
    ensure!(
        !log.contains("LaTeX Warning:")
            && !log.contains("Package hyperref Warning:")
            && !log.contains("Overfull ")
            && !log.contains("undefined references"),
        "paper warnings/overflow; staged output not installed"
    );
    let papers = stage.join("www/project/static/papers");
    fs::create_dir_all(&papers)?;
    let pdf = papers.join("bevy_zeroverse.pdf");
    fs::copy(build.join(format!("{stem}.pdf")), &pdf)?;
    let preview = build.join("whitepaper");
    ensure!(
        Command::new("pdftoppm")
            .args(["-f", "1", "-singlefile", "-scale-to", "1000", "-png"])
            .arg(&pdf)
            .arg(&preview)
            .status()
            .context("Poppler pdftoppm is required")?
            .success(),
        "paper preview failed"
    );
    crate::graphics::save_webp(
        image::open(preview.with_extension("png"))?.into_rgb8(),
        &stage.join("www/project/static/media/whitepaper.webp"),
    )?;
    let mut entries = BTreeMap::new();
    let mut sources = BTreeMap::new();
    for path in closure(&tex_root, main)? {
        let name = path.to_string_lossy().replace('\\', "/");
        sources.insert(format!("tex/{name}"), io::hash(&tex_root.join(&path))?);
        entries.insert(name, fs::read(tex_root.join(path))?);
    }
    entries.insert("BUILD.txt".into(),format!("Run latexmk -pdf -no-shell-escape bevy_zeroverse.tex.\nCurrent dataset: crate {}, generator {}, {} audited programs and {} six-mode camera/time views. References retain their original identities.\n",gallery["generator_identity"]["crate_version"].as_str().unwrap(),gallery["generator_version"],gallery["audit_rooms"],gallery["rendered_views"]).into_bytes());
    io::archive(&papers.join("whitepaper-source.zip"), &entries)?;
    io::write(
        &papers.join("provenance.json"),
        &json!({"schema_version":2,"generator_identity":gallery["generator_identity"],"pdf_sha256":io::hash(&pdf)?,"source_archive_sha256":io::hash(&papers.join("whitepaper-source.zip"))?,"sources":sources,"architecture_gallery_sha256":io::hash(&stage.join("www/project/static/media/architecture/gallery.json"))?,"build":"bevy_zeroverse_publication refresh; latexmk -pdf -no-shell-escape","scope":"Main results and all-six-mode gallery share one verified current capture run. Reference appendix studies retain separate recorded identities."}),
    )?;
    Ok(())
}
