FROM rust:latest
# FROM nvcr.io/nvidia/pytorch:23.10-py3

RUN apt-get update && apt-get install -y \
    g++ \
    pkg-config \
    libx11-dev \
    libasound2-dev \
    libudev-dev \
    libxkbcommon-x11-0 \
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
