name: clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  clippy:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, macos-14]
        rust-toolchain:
          - nightly

    runs-on: ${{ matrix.os }}
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v3

    - name: Setup ${{ matrix.rust-toolchain }} rust toolchain with caching
      uses: brndnmtthws/rust-action@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rustfmt, clippy
        enable-sccache: "true"

    - name: lint
      run: cargo clippy -- -Dwarnings
