name: 'build LaTeX document'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: 'latest'

      - name: Run Tectonic
        run: tectonic tex/bevy_zeroverse.tex

      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: bevy_zeroverse
          path: tex/bevy_zeroverse.pdf
