//! Action phrases and their physical requirements are one catalog. Templates use
//! concrete body actions; no furniture or held props are invented by the grammar.
use super::Family;

#[derive(Clone, Copy)]
pub(super) struct Action {
    pub id: &'static str,
    pub family: Family,
    pub phrase: &'static str,
    pub radius: f32,
    pub headroom: f32,
    pub minimum_frames: usize,
    pub peak_height: [f32; 2],
    pub repeatable: bool,
    pub seated: bool,
    pub turn: bool,
}

macro_rules! action {
    ($id:ident, $family:ident, $phrase:literal, $radius:literal, $headroom:literal, $frames:literal, [$low:literal, $high:literal], $repeat:literal, $seated:literal, $turn:literal) => {
        Action {
            id: stringify!($id),
            family: Family::$family,
            phrase: $phrase,
            radius: $radius,
            headroom: $headroom,
            minimum_frames: $frames,
            peak_height: [$low, $high],
            repeatable: $repeat,
            seated: $seated,
            turn: $turn,
        }
    };
}

pub(super) const ACTIONS: &[Action] = &[
    action!(
        wave,
        Gesture,
        "waves the {hand} hand {count}",
        0.80,
        0.05,
        24,
        [0.92, 0.96],
        true,
        true,
        false
    ),
    action!(
        point,
        Gesture,
        "points {side} with the {hand} hand",
        0.90,
        0.0,
        28,
        [0.92, 0.96],
        false,
        true,
        false
    ),
    action!(
        clap,
        Gesture,
        "claps both hands {count}",
        0.65,
        0.0,
        22,
        [0.92, 0.96],
        true,
        true,
        false
    ),
    action!(
        beckon,
        Gesture,
        "beckons with the {hand} hand {count}",
        0.75,
        0.0,
        24,
        [0.92, 0.96],
        true,
        true,
        false
    ),
    action!(
        shrug,
        Gesture,
        "shrugs both shoulders {count}",
        0.60,
        0.0,
        24,
        [0.92, 0.96],
        true,
        true,
        false
    ),
    action!(
        explain,
        Gesture,
        "explains with {size} gestures of both hands",
        0.80,
        0.0,
        32,
        [0.92, 0.96],
        false,
        true,
        false
    ),
    action!(
        stop_sign,
        Gesture,
        "holds the {hand} palm forward, then lowers it",
        0.75,
        0.0,
        28,
        [0.92, 0.96],
        false,
        true,
        false
    ),
    action!(
        salute,
        Gesture,
        "salutes with the {hand} hand, then relaxes",
        0.65,
        0.0,
        28,
        [0.92, 0.96],
        false,
        true,
        false
    ),
    action!(
        rub_hands,
        Gesture,
        "rubs both hands together",
        0.55,
        0.0,
        28,
        [0.92, 0.96],
        false,
        true,
        false
    ),
    action!(
        chest_touch,
        Gesture,
        "touches the chest with the {hand} hand",
        0.55,
        0.0,
        24,
        [0.92, 0.96],
        false,
        true,
        false
    ),
    action!(
        squat,
        Exercise,
        "squats {count} and straightens up",
        0.85,
        0.0,
        36,
        [0.43, 0.65],
        true,
        false,
        false
    ),
    action!(
        lunge,
        Exercise,
        "lunges with the {side} leg and returns",
        1.15,
        0.0,
        40,
        [0.65, 0.80],
        false,
        false,
        false
    ),
    action!(
        knee_raise,
        Exercise,
        "raises the {side} knee {count}",
        0.90,
        0.0,
        30,
        [0.90, 0.97],
        true,
        false,
        false
    ),
    action!(
        kick,
        Exercise,
        "kicks forward with the {side} leg {count}",
        1.25,
        0.0,
        34,
        [0.90, 0.97],
        true,
        false,
        false
    ),
    action!(
        jump,
        Exercise,
        "jumps upward {count} and lands",
        1.10,
        0.55,
        32,
        [1.15, 1.35],
        true,
        false,
        false
    ),
    action!(
        jumping_jack,
        Exercise,
        "does jumping jacks {count}",
        1.20,
        0.65,
        32,
        [1.05, 1.18],
        true,
        false,
        false
    ),
    action!(
        calf_raise,
        Exercise,
        "rises onto both toes {count}",
        0.65,
        0.15,
        28,
        [1.00, 1.06],
        true,
        false,
        false
    ),
    action!(
        arm_circle,
        Exercise,
        "circles both arms {count}",
        1.15,
        0.45,
        32,
        [0.92, 0.96],
        true,
        false,
        false
    ),
    action!(
        side_bend,
        Exercise,
        "bends the torso {side}, then straightens",
        0.95,
        0.0,
        32,
        [0.82, 0.92],
        false,
        false,
        false
    ),
    action!(
        overhead_reach,
        Exercise,
        "reaches both arms overhead, then lowers them",
        0.95,
        0.50,
        32,
        [0.94, 0.99],
        false,
        false,
        false
    ),
    action!(
        box,
        Exercise,
        "punches forward with the {hand} arm {count}",
        1.05,
        0.0,
        28,
        [0.88, 0.95],
        true,
        false,
        false
    ),
    action!(
        balance,
        Exercise,
        "balances on the {side} foot, then relaxes",
        0.80,
        0.0,
        36,
        [0.92, 0.96],
        false,
        false,
        false
    ),
    action!(
        sway,
        Dance,
        "sways the hips {side} and back {count}",
        0.80,
        0.0,
        28,
        [0.88, 0.95],
        true,
        false,
        false
    ),
    action!(
        step_touch,
        Dance,
        "does {size} step touches from side to side",
        1.10,
        0.0,
        40,
        [0.90, 0.97],
        false,
        false,
        false
    ),
    action!(
        heel_tap,
        Dance,
        "taps the {side} heel {count}",
        0.85,
        0.0,
        24,
        [0.90, 0.97],
        true,
        false,
        false
    ),
    action!(
        shoulder_dance,
        Dance,
        "bounces both shoulders in a {rhythm} rhythm",
        0.65,
        0.0,
        32,
        [0.87, 0.97],
        false,
        true,
        false
    ),
    action!(
        dance_turn,
        Dance,
        "turns {side}, then faces forward again",
        0.85,
        0.0,
        40,
        [0.92, 0.96],
        false,
        false,
        true
    ),
    action!(
        pick_up,
        Floor,
        "bends to pick something up with the {hand} hand",
        0.95,
        0.0,
        48,
        [0.38, 0.58],
        false,
        false,
        false
    ),
    action!(
        crouch,
        Floor,
        "crouches to inspect the floor, then stands",
        0.90,
        0.0,
        44,
        [0.40, 0.60],
        false,
        false,
        false
    ),
    action!(
        kneel,
        Floor,
        "kneels on the {side} knee, then gets up",
        1.10,
        0.0,
        56,
        [0.37, 0.51],
        false,
        false,
        false
    ),
    action!(
        touch_floor,
        Floor,
        "touches the floor with the {hand} hand",
        0.95,
        0.0,
        40,
        [0.48, 0.65],
        false,
        false,
        false
    ),
    action!(
        fall_recover,
        Floor,
        "falls {side}, then gets back to the feet",
        1.65,
        0.0,
        88,
        [0.18, 0.30],
        false,
        false,
        false
    ),
    action!(
        sit_floor,
        Floor,
        "sits on the floor, then gets up",
        1.25,
        0.0,
        72,
        [0.18, 0.32],
        false,
        false,
        false
    ),
    action!(
        look,
        Idle,
        "looks over the {side} shoulder, then forward",
        0.55,
        0.0,
        28,
        [0.92, 0.96],
        false,
        true,
        false
    ),
    action!(
        nod,
        Idle,
        "nods the head {count}",
        0.55,
        0.0,
        20,
        [0.92, 0.96],
        true,
        true,
        false
    ),
    action!(
        head_shake,
        Idle,
        "shakes the head {count}",
        0.55,
        0.0,
        24,
        [0.92, 0.96],
        true,
        true,
        false
    ),
    action!(
        shoulder_roll,
        Idle,
        "rolls both shoulders {count}",
        0.60,
        0.0,
        28,
        [0.92, 0.96],
        true,
        true,
        false
    ),
    action!(
        weight_shift,
        Idle,
        "shifts weight onto the {side} foot and back",
        0.60,
        0.0,
        32,
        [0.91, 0.97],
        false,
        false,
        false
    ),
    action!(
        fold_arms,
        Idle,
        "folds both arms, pauses, then relaxes",
        0.55,
        0.0,
        32,
        [0.92, 0.96],
        false,
        true,
        false
    ),
    action!(
        head_scratch,
        Idle,
        "scratches the head with the {hand} hand",
        0.65,
        0.0,
        28,
        [0.92, 0.96],
        false,
        true,
        false
    ),
];
